### PR TITLE
BaSP-MR-117: Admins Reports

### PR DESCRIPTION
**Pull request by Bigzufi**
Captura de Pantalla 2023-06-24 a la(s) 02 50 43

- Add  a reports component for the admins.
- Reports of members (total, active, membership active)
- Reports type of membership chosen
- Reports of popular classes subscribed for members

### CODE REVIEW

**Review by SantiH97 — CHANGES_REQUESTED** [review]
I see youre still missing quite a bit of CSS, I would advice following the iniciative of the profile page, with one blue rectangle per category, Also the week 01 file states that admins should get reports from members and not any other entities
chrome_ai6OlDOf6H

**Review by DelfiLT — CHANGES_REQUESTED** [review]
When I click reports the page crashes

**Comment by Bigzufi** [comment]
> When I click reports the page crashes

Fixed

**Comment by Bigzufi** [comment]
> I see youre still missing quite a bit of CSS, I would advice following the iniciative of the profile page, with one blue rectangle per category, Also the week 01 file states that admins should get reports from members and not any other entities chrome_ai6OlDOf6H

The CSS has been corrected. As indicated by the tag, this branch was a work in progress, but now I think it's ready. Regarding the reports of the other entities, it actually refers to their relationship with the members, which is why I believe it is relevant information

**Comment by Bigzufi** [comment]
[Admin reports](https://trello.com/c/5Lz1jltD/117-admin-reports)

**Review by SantiH97 — APPROVED** [review]

**Review by DelfiLT — APPROVED** [review]

**Pull request merged**
