### PR TITLE
 BaSP-MR-111: Members(Class, Subscribe)

### PR DESCRIPTION
**Pull request by DelfiLT**
- Modified the classes table to show only information to members
- Modified the subscriptions table to not show the edit button and to show only this member subscriptions
- Modified the subscriptions form to not show the member selector(the member is sent automatically)
- Fixed the classes table style according to the ticket MR-116
- Made a provisional style for the home page

### CODE REVIEW

**Review by ukiweskamp — APPROVED** [review]
I think there are issues that need to be improved in css but we can do it once all the forms are merged and we define all the tables and forms

**Comment by ukiweskamp** [comment]
> > I think there are issues that need to be improved in css but we can do it once all the forms are merged and we define all the tables and forms
> 
> Wich ones?


At least in the vercel preview this is what happens when you enter the classes:
https://imgur.com/a/2mfIRXQ

The bottom border below the th is not the same width in classes and in my subscriptions

**Review by SantiH97 — APPROVED** [review]
All set up nice and pretty as allways :)

**Review by Eliezer-Alberto — APPROVED** [review]
Very Good Job!.. ;)

**Pull request merged**
