### PR TITLE
BaSP-MR-49: Set up folder structure and routing

### PR DESCRIPTION
**Pull request by SantiH97**
I made the shared folder with its corresponding componet folders and basic empty files to get us started. I also managed to install React Routes and set up all routes with said library as well as changed all .js files to .jsx (I thought I might as well). This time I remembered not to push those pesky .json flies

### CODE REVIEW

**Comment by SantiH97** [comment]
[Setup - Week 12](https://trello.com/c/fnk7PrwH/49-setup-week-12)

**Review by DelfiLT — CHANGES_REQUESTED** [review]
Missin package.json so we can install new dependencies, thats why vercel isn't deploying either, it can't find the react dom dependency

**Review by ukiweskamp — APPROVED** [review]
Good work Santi !

**Review by DelfiLT — APPROVED** [review]

**Comment by SantiH97** [comment]
[Activities - HOTFIX](https://trello.com/c/jKbgFO4e/67-activities-hotfix)

**Pull request merged**
